### ISSUE TITLE
Chrome Shortcut: Possible issue with minimum chars on profile name

### ISSUE THREAD

**Issue by derek-shnosh** [felipecrs/dotfiles#119]
This isn't an issue with the script, because it does what it's intended to do. However, it seems Chrome may require at least 3 characters in the data dir name; that's my hypothesis after some testing. I spent some time trying to find supporting documentation but had no luck.

Using Gnome 46 (Ubuntu 24.04), I used the script to create a profile named **AB** and then pinned it to the dock. If I click the icon or hit the <kbd>META</kbd>+<kbd>#</kbd> associated with its location on the dock, it launches a new instance of Chrome every time.

I also noticed that clicking the pinned icon would create a new Chrome icon in my dock instead of putting a marker underneath the pinned icon. Hovering over the icon in the dock, it simply showed **Google Chrome** instead of **Google Chrome (AB)** (from the `name=` setting in the .desktop file).

I then used the script to create a profile named **ABC** and pinned it to the dock; this worked as intended.

**Comment by felipecrs** [comment]
Very interesting. I'll keep this issue open until I can test it as well. If confirmed, I can add a safety check to reject creating the shortcut if the name is shorter than 2 chars.

**Comment by derek-shnosh** [comment]
Another option would be to accept the profile name, but append $n$ (1 or 2) underscores to the data dir as needed.

E.g., User input is **P1**, script names profile as requested but creates data dir as **P1_** (or **_P1**).

**Comment by felipecrs** [comment]
Right, but I'd rather let the user be aware of the limitation and make the adjustments on their own.

**Comment by derek-shnosh** [comment]
Eh, maybe off base. Yesterday I recreated an **ABC** profile and it was working fine all day, but the behavior listed in my original post is back now, with only that profile.

I still don't think it's a script issue. Absolutely curious if you see this behavior on your end though.

FYI - this is my 3rd profile I have setup and pinned to my _dock_.

Profile 1: FOO -- working fine
Profile 2: BAR -- working fine
Profile 3: ABC -- behavior as outlined in my original post.

**Comment by felipecrs** [comment]
I was not able to reproduce the behavior you described. Can you please:

```
cat ~/.local/share/applications/google-chrome-abc.desktop 
```

**Comment by derek-shnosh** [comment]
```desktop
[Desktop Entry]
Version=1.0
Name=Google Chrome (ABC)
GenericName=Web Browser
Comment=Access the Internet
Exec=/usr/bin/google-chrome-stable --class=google-chrome-abc --user-data-dir=/home/ds/.config/google-chrome-abc %U
StartupNotify=true
Terminal=false
Icon=google-chrome
Type=Application
Categories=Network;WebBrowser;
MimeType=application/pdf;application/rdf+xml;application/rss+xml;application/xhtml+xml;application/xhtml_xml;application/xml;image/gif;image/jpeg;image/png;image/webp;text/html;text/xml;x-scheme-handler/http;x-scheme-handler/https;
Actions=new-window;new-private-window;

[Desktop Action new-window]
Name=New Window
Exec=/usr/bin/google-chrome-stable --class=google-chrome-abc --user-data-dir=/home/ds/.config/google-chrome-abc

[Desktop Action new-private-window]
Name=New Incognito Window
Exec=/usr/bin/google-chrome-stable --class=google-chrome-abc --user-data-dir=/home/ds/.config/google-chrome-abc --incognito
```

**Comment by derek-shnosh** [comment]
Had a few mins to poke at this today. Made some progress, but no resolution.

The profile I'm having issues with has some webapps, e.g., Outlook PWA, that I use frequently, or are open throughout the day.

If any webapp is open (installed under that profile) when I click the pinned icon, a new instance will launch, completely ignoring the `--class` arg in the **.desktop** file.

I'm going to have to find some time to figure out how to work around this.
