### ISSUE TITLE
A little idea

### ISSUE THREAD

**Issue by MuXiu1997** [felipecrs/dotfiles#49]
Maybe you can generate a json file based on `github action` to get all the data you need from http requests (or something else) and store it in a `gist`
In your template, you only need one http request with `fromJson` to get all the data
You can use `schedule` trigger to keep the data up to date

**Comment by felipecrs** [comment]
That's interesting, but I'm not sure if I like the idea of having my dotfiles dependent that much on an external resource managed by me.

I'm yet thinking...

**Comment by felipecrs** [comment]
Your idea is really cool, but for now I would prefer to not tie the installation of my dotfiles to an external computer running a job like this.

Also because I use my dotfiles as base in the company I work, and there we don't use GitHub Actions at all.

I just merged https://github.com/felipecrs/dotfiles/pull/51 which solves my problem at some sort.

**Comment by MuXiu1997** [comment]
> The problem I found about {{- if not (eq (index .chezmoi.args 1) "execute-template") -}} was that, if I'm executing the following:
> 
> $ cat ~/.dotfiles/home/.chezmoiexternal.yaml | time chezmoi execute-template
> It skips the template as well.
> 
> I ended up doing this: felipecrs/dotfiles#51

I can't reply in twpayne/chezmoi#1662

```sh
chezmoi execute-template "$(cat .chezmoiexternal.yaml | sed '$d' | sed '15d')" | bat -l yaml
```

**Comment by felipecrs** [comment]
Got it. There is also this option:

```
$ chezmoi --force execute-template "$(cat .chezmoiexternal.yaml)"
```

**Comment by MuXiu1997** [comment]
Fantastic, I didn't even know it could be used like this
But I have tested it many times, --force is 0.8 seconds, without --force only takes 0.4 seconds
