### ISSUE TITLE
Suggestion help ?

### ISSUE THREAD

**Issue by Decapitater** [felipecrs/dotfiles#65]
I like this project a lot , easily bootstrap Ubuntu with dotfiles. I was thinking of doing it in arch is it vailable ?

**Comment by felipecrs** [comment]
Hey, I'm glad that you like it.

Ultimately I would want it to be compatible with other distros as well.

But supporting more distros would require some tinkering. It's nothing too much complicated, it's needed to check all the scripts and replace the commands accordingly. For example, on Arch, one should replace `apt` with `pacman`, so on and so forth.

Here is an example:

```bash
# {{ if eq .chezmoi.osRelease.id "ubuntu" }}
sudo apt install --yes --no-install-recommends zsh
# {{ else if eq .chezmoi.osRelease.id "arch" }}
sudo pacman -Sy zsh
# {{ end }}
```

Personally, I don't plan to add support for Arch anytime soon, so I would suggest you to fork the project and make the changes there as you wish.

Thanks a lot for raising this anyway!
